name: Fetch and Save to DB

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data fetch script
        env:
          SWITCHBOT_TOKEN: ${{ secrets.SWITCHBOT_TOKEN }}
        run: python app.py

      - name: Commit DB changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add db.sqlite3
          git commit -m "Update DB: $(date)" || echo "No changes to commit"
          git push
